spring.datasource.url=mysql://root:kMqsalLTQMrxBFQlIKFyHUpYBhGhkKPh@trolley.proxy.rlwy.net:21184/railway
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=kMqsalLTQMrxBFQlIKFyHUpYBhGhkKPh

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

server.port=${PORT:8080}