spring.datasource.url=mysql://root:kMqsalLTQMrxBFQlIKFyHUpYBhGhkKPh@trolley.proxy.rlwy.net:21184/railway
spring.datasource.username=root
spring.datasource.password=kMqsalLTQMrxBFQlIKFyHUpYBhGhkKPh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect



server.port=${PORT:8080}