spring.datasource.url=jdbc:mysql://trolley.proxy.rlwy.net:21184/railway?useSSL=true&requireSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=kMqsalLTQMrxBFQlIKFyHUpYBhGhkKPh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}